In [2]:
import numpy as np
import pandas as pd

In [3]:
data = [[21, 'Manoj', 26], [22, 'Akshay', 30], [23, 'Gaurav', 41]]

In [4]:
columns = ['ID', 'Name', 'rollno']

In [5]:
df = pd.DataFrame(data, columns=columns)

In [6]:
print(df)

   ID    Name  rollno
0  21   Manoj      26
1  22  Akshay      30
2  23  Gaurav      41


In [7]:
data = {'ID': [1, 2, 3], 'Name': ['manoj', 'akshay', 'gaurav'], 'rollno': [25, 30, 35]}

In [8]:
df = pd.DataFrame(data)

In [9]:
print(df)

   ID    Name  rollno
0   1   manoj      25
1   2  akshay      30
2   3  gaurav      35


In [10]:
filter_df = df[df['rollno'] > 26]

In [11]:
print(filter_df)

   ID    Name  rollno
1   2  akshay      30
2   3  gaurav      35


In [12]:
filtered_df = df[['ID', 'Name']]

In [13]:
print(filtered_df)

   ID    Name
0   1   manoj
1   2  akshay
2   3  gaurav


In [14]:
df.replace({'manoj': 'mahesh', 35: 26}, inplace=True)

In [15]:
print(df)

   ID    Name  rollno
0   1  mahesh      25
1   2  akshay      30
2   3  gaurav      26


# Creating two DataFrames with random data

In [16]:
np.random.seed(123)

In [17]:
df1 = pd.DataFrame(np.random.randint(0, 10, size=(10, 3)), columns=['A', 'B', 'C'])

In [23]:
df2 = pd.DataFrame(np.random.randint(0, 10, size=(10, 3)), columns=['A', 'B', 'C'])

In [24]:
pd.concat([df1, df2])

A  B  C
0  2  4  8
1  1  2  1
2  1  3  5
3  9  0  8
4  1  6  3
5  3  5  9
6  7  9  2
7  3  3  3
8  8  6  9
9  7  6  3
0  9  6  6
1  6  1  3
2  4  3  1
3  0  5  8
4  6  8  9
5  1  0  3
6  1  3  4
7  7  6  1
8  4  3  3
9  7  6  8

In [6]:
df1 = pd.DataFrame(np.random.randint(0, 10, size=(10, 3)), columns=['A', 'B', 'C'])

In [7]:
print(df1.head())

   A  B  C
0  7  9  6
1  3  8  4
2  2  4  1
3  0  2  0
4  0  1  9


In [8]:
arr1 = np.arange(9).reshape(3,3)

In [9]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr2 = np.arange(5,14).reshape(3,3)

In [12]:
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [13]:
add = arr1 + arr2

In [14]:
add

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])